export const showcaseArr = [
  {
    lineOne: 'FIREBASE',
    lineTwo: 'property rental site',
    fullStack: true,
    link: 'https://www.smart-property.biz/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Fsmart.png?alt=media&token=431db1a8-b996-4525-8963-39769787a8ee',
    gitLink: '',
    show: true,
    order: 1,
  },
  {
    lineOne: 'PYTHON - REACT',
    lineTwo: 'e commerce shop',
    fullStack: true,
    link: 'https://easy-shop.biz/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Feasy-store.png?alt=media&token=452d74ee-9f57-4c00-aee8-c4644f5956fe',
    gitLink: '',
    show: true,
    order: 2,
  },
  {
    lineOne: 'FIREBASE',
    lineTwo: 'CRM system',
    fullStack: true,
    link: 'https://easy-data.biz/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Feasy-data.png?alt=media&token=987d6bc0-edd6-4612-993d-11d9b333df88',
    gitLink: '',
    show: true,
    order: 3,
  },
  {
    lineOne: 'MERN',
    lineTwo: 'e commerce shop',
    fullStack: true,
    link: 'https://jungle-store-frontend.vercel.app/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Fjungle.png?alt=media&token=9a22056c-41bd-4222-ad04-1441b1114f1f',
    gitLink: '',
    show: true,
    order: 4,
  },
  {
    lineOne: 'MERN',
    lineTwo: 'content managment system',
    fullStack: true,
    link: 'https://www.thetravel.blog/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Fcms-blog.png?alt=media&token=b3a80260-d8db-4843-a1cf-d9559816dfc6',
    gitLink: '',
    show: true,
    order: 5,
  },
  {
    lineOne: 'VANILLA JAVASCRIPT',
    lineTwo: 'e commerce shop',
    fullStack: false,
    link: 'https://vanilla-js-shop-updated.vercel.app/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Fvanilla-shop.png?alt=media&token=a55f7495-2524-45a1-8352-9db207646a71',
    gitLink: '',
    show: true,
    order: 6,
  },
  {
    lineOne: 'FIREBASE',
    lineTwo: 'admin functionality',
    fullStack: false,
    link: 'https://firebase-admin-pannel-updated.vercel.app/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Ffirebase-admin.png?alt=media&token=4aabd2a0-e254-4deb-9873-82196da15014',
    gitLink: '',
    show: true,
    order: 7,
  },
  {
    lineOne: 'VANILLA JAVASCRIPT',
    lineTwo: 'travel landing page super nav',
    fullStack: false,
    link: 'https://travel-blaze-updated.vercel.app/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Ftravel-landing-page.png?alt=media&token=05eada7f-d017-4356-bde4-ab6b4de484e0',
    gitLink: '',
    show: true,
    order: 8,
  },
  {
    lineOne: 'REACT FRONTEND',
    lineTwo: 'e commerce shop',
    fullStack: false,
    link: 'https://comfy-store-course-react-router-6-4.vercel.app/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Fcomfy-project.png?alt=media&token=9fd95778-be74-4efc-be4d-bb0fe18a57e9',
    gitLink: '',
    show: true,
    order: 9,
  },
  {
    lineOne: 'MERN',
    lineTwo: 'job search tracking site',
    fullStack: false,
    link: 'https://jobify-frontend-olive.vercel.app/',
    url: 'https://firebasestorage.googleapis.com/v0/b/my-portfolio-app-90783.firebasestorage.app/o/project%20images%2Fjobify.png?alt=media&token=b85881e6-6f45-4a40-9fa4-018888dd7a6a',
    gitLink: '',
    show: true,
    order: 10,
  },
]
